language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

install: composer install --dev

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

notifications:
  email: false
  slack:
    secure: AMm9tohhZuxfd8+N3+8d32F9qXT6l9k4d3zLBJ9U1KoTPiRtRaaCbhEDItHDLAhXLc+JEmBM8Z4QCnKzk18CajUwlzVStzneZFHxGPD7J4R+fjNqcKRhinOUHBTqlBGd1afCDCk/l1U+Unyq3ytC1lcVbDX0qHgerASILAmZTA4=
